okken/pytest-check

README.rst, src/pytest_check/plugin.py
fix(NameError) add msg param in check methods, by default None
add(readme) usage and requirements
Changes:
-   README.rst
-   src/pytest_check/plugin.py
=> fix(NameError) add msg param in check methods, by default None

README.md, setup.py, src/pytest_check/check_methods.py, tests/test_check_context_manager.py
As mentioned in https://github.com/okken/pytest-check/issues/9#issuecomment-466701960
So I still use python 2.7 🙄 
PS. How come you're not using pytest-cov?
=> Remove extra function call from context manger API

src/pytest_check/check_methods.py
More details in https://github.com/okken/pytest-check/issues/21
Ran tests in tox and looks good. No need to add/modify any tests.
Didn't bump version nr (not sure if needed to).
=> Failure report with pattern `<filename>:<line_nr>`

src/pytest_check/plugin.py, tests/test_check.py
Hi, 
I've been using the pytest-check tool and noticed that fail(strict=True) is not supported. 
This update has worked for me locally.
Ciao, 
derirreIre
=> Adding the xfail(strict=True) support

README.md
The `is_not_instance` is described as `not_is_instance` in the `README.MD`, as described in #27 . This little patch is intended to fix it.
=> Fix `is_not_instance` doc inconsistency in README.md

src/pytest_check/check_methods.py, tests/conftest.py, tests/test_check_context_manager.py
This adds a msg attribute to CheckContextManager. This is set to None by default, but can be changed by calling `check`. If set, failures inside the `check` context are logged with this message, instead of simply the assertion error.
This is useful if multiple checks all test for roughly the same thing, and you want to log them all in the same context, e.g.:
`test_a_class.py`
```python
from dataclasses import dataclass
from pytest_check import check
@dataclass
class A:
name: str = ""
value: float = 1
def test_class_a():
with check("test default parameters of A"):
a = A()
assert a.name == ""
assert a.value == 0
```
This now gets logged as:
```
=================================== FAILURES ===================================
________________________________ test_failures …
```
=> Add a "msg" parameter to check context manager

azure-pipelines.yml, src/pytest_check/__init__.py, src/pytest_check/check_methods.py, tests/test_check.py, tox.ini
- revert PR 35, check.raises, due to incomplete test coverage
- increase coverage to 100% code & branch
- add py38 testing
- add testing of pytest 5.3, since the 5.4 behavior change caused conditional code
- change tox.ini to combine coverage over multiple test runs
- a flake8 fix
=> Increase coverage to 100% with tests against multiple pytest versions

src/pytest_check/check_methods.py
=> Fix get_full_context() finding filename path

src/pytest_check/plugin.py
Try to fix #57. Also link to https://github.com/allure-framework/allure-python/issues/376
Now allure normally received exception info
Maybe need some small formatting changes and tests
@okken How can we test it? Add integration test with `allure-pytest` installation?
=> Add excinfo to `call` object if an exception has occurred

.gitignore, README.md, src/pytest_check/__init__.py, src/pytest_check/check_methods.py, tests/test_check_raises.py, tox.ini
CC @okken @dillonm197
Retrying https://github.com/okken/pytest-check/pull/35.
Add a new method, `raises`, modeled after `pytest.raises` that checks that an assertion of a given type is raised by a code block.
Love the Python Bytes podcast, by the way, @okken.  I was astounded when I realized you were the same "Okken" as the one whose repo I commented on!
We've tried to add a `raises` method in both https://github.com/okken/pytest-check/pull/35 and before that https://github.com/okken/pytest-check/pull/33.  However, test coverage was lacking and the submitted version couldn't be used as a function as well as a context manager, which fits some of my use cases.
I added an amended form of `raises` that is modeled off of `pytest.raises` such that they have similar call signatures (i.e. support …
=> Attempt 2: Add check raises with test coverage

changelog.md, examples/test_example_check_check.py, src/pytest_check/__init__.py, tests/test_check_check.py
Make this work:
```python
def test_check_check(check):
"Deprecated, but should still work for now"
with check.check:
assert True
```
=> Allow check.check as a context manager when using check fixture

README.md, examples/test_example_any_failures.py, src/pytest_check/__init__.py, src/pytest_check/check_log.py, tests/test_any_failures.py
First of all thanks for this pytest plugin (we started to use it around 6 months ago). And we implemented very soon on our side this any_failures() function to check a container deployment:
* First we have a first group of checks for the init_container, 
* And second we have a second group of checks for the container. So it has no sense to keep running these second checks if any previous init_container check has failed. Also this help to reduce noise when checking results
Due to your recent refactoring, It broke the our customized any_failures, so It decided me to prepare this PR so anyone can also reuse this simple change:
- Including boolean any_failure() function and its import. 
- Adding unitary tests
- And adding a short explanation to readme 
Note: A typo is also fixed, and some …
=> Add any_failures function to skip further checking if any failure due to a first group of checks

README.md
Some user (me included) use conda to manage their python envs.
I saw that `pytest-check` is available in conda-forge artifact repository: https://github.com/conda-forge/pytest_check-feedstock
but this is not obvious when reading the Readme.
This PR fixes this by adding the instruction on how to install pytest-check from conda-forge.
=> DOC: Add conda installation instruction

README.md, changelog.md, examples/test_example_speedup_funcs.py, src/pytest_check/__init__.py, src/pytest_check/check_log.py, src/pytest_check/context_manager.py, src/pytest_check/plugin.py, tests/test_helpers.py, tests/test_speedup_flags.py, tests/test_speedup_functions.py
The default behavior has changed. Since `--check-max-tb=1` is the default, the default behavior is now:
- Show traceback for the first failure per test. (controlled by `--check-max-tb`, default is 1)
- Show error report for the remaining failures in a test. (controlled by `--check-max-report`, default is None)
Old default behavior was the same except all tracebacks would be reported.
My logic here:
- The actual error message, like `check 1 == 3`, is more useful than the traceback.
- The first traceback is still useful to point you to the test file, line number, of first failure.
- Other failures are probably close by. 
If this logic doesn't hold for you, you can always set `--check-max-tb=1000` or some other large number.
=> 2.0.0 - new --check-max-tb, defaults to 1, deprecate --check-no-tb

README.md, examples/test_example_logging.py, src/pytest_check/check_log.py, src/pytest_check/plugin.py, tests/test_logging.py
Thanks again for this plugin. And second PR to this repo :tada: 
Just to add an option to be able to see failures inside log as they appear
Currently you can see all the failures together in the final exception, and so every individual failure can not be related with the rest of your logging.
I have made it optional so behavior is not modified without the option.
And added new unit tests for new code
Please let me know your kind feedback.
=> Add option for logging every individual failure

README.md
Just fix a documentation issue related to check-max-tb parameter, and also try to improve the description of this parameter
Note: My user case is to select a big number, 1000, in order to have always pseudo-tracebacks
=> check-max-tb parameter: Fix documentation typo and improve description

pyproject.toml
The switch to flit has resulted in examples and tests disappearing from sdist.  Linux distributions need the latter to test the package. Explicitly include all useful files.
=> readd tests and examples to sdist

examples/test_example_fail_in_thread.py, examples/test_example_pass_in_thread.py, src/pytest_check/pseudo_traceback.py, tests/test_thread.py
Fix issue #127 
In a thread, the pseudo-traceback looks like:
```
_________ test_threadpool __________
FAILURE: check 2 == 3: 1 + 1 is 2, not 3
../../../../usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py:995 in _bootstrap() -> self._bootstrap_inner()
../../../../usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py:1038 in _bootstrap_inner() -> self.run()
../../../../usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py:975 in run() -> self._target(*self._args, **self._kwargs)
../../../../usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py:83 in _worker() -> …
```
=> Fix traceback construction in tests using threadpool

pyproject.toml
Fixes #135
This changes the supported Python version specification to `">=3.7"`. Prior to this change it was `">3.7"`, which is equivalent to `">=3.7.1"`, and which I believe does not clearly express intent.
See #135 for details (including on other approaches besides this one).
=> Give Python lower bound with ">=" instead of ">"

examples/test_example_short_test_summary_info.py, src/pytest_check/plugin.py, tests/test_short_test_summary_info.py
Fixes #133 
add additional info to short test summary info.
The message is FAILURES's first message.
I believe that even if there are multiple error messages, it is sufficient if even one is displayed in the short message
```
FAILURE: check 1 == 2: comment about a=1 != b=2
```
```
============================= test session starts ==============================
platform linux -- Python 3.7.9, pytest-7.4.3, pluggy-1.2.0
rootdir: /tmp/pytest-of-mizubuntu/pytest-75/test_message0
plugins: check-2.2.2
collected 2 items / 1 deselected / 1 selected
test_example_short_test_summary_info.py F                                [100%]
=================================== FAILURES ===================================
_________________________________ test_message _________________________________
FAILURE: …
```
=> Add short test summary info result message

src/pytest_check/plugin.py
Hi @okken,
Thanks for this package! 
This small PR fixes an issue I encountered when running pytest with `-p no:terminal`. It seems that some of the options the plugin expects don't exist when the terminal is disabled. Here's an example of the issue:
```bash
> pytest -p no:terminal
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/rutherford/.env38/lib/python3.8/site-packages/_pytest/main.py", line 266, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/rutherford/.env38/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1037, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/rutherford/.env38/lib/python3.8/site-packages/pluggy/_hooks …
```
=> Support running pytest with -p no:terminal

changelog.md, pyproject.toml, src/pytest_check/plugin.py
Fix for #155 
The summary logic doesn't work with xdist.
For now, turn off summaries when xdist is running.
=> Fix #155, turn off summaries with xdist

README.md, changelog.md, examples/test_example_fail_func.py, examples/test_example_fail_in_thread.py, examples/test_example_pass_in_thread.py, pyproject.toml
Documentation Update
- README.md
- Turn help function list into a table with param lists
- Show an alternative method of creating a helper function using `check.fail()`
- examples
- change a few remaining `import pytest_check as check` examples
-  to the recommended `from pytest_check import check`
=> doc update

src/pytest_check/plugin.py, tests/test_xfail.py
Add a check in `pytest_runtest_makereport` that skips `xfail` handling if `runxfail` option is set.
Adds a test for this behaviour.
Resolves #171
=> Fix check ignoring runxfail option

pyproject.toml
Might as well cull this obsolete config?
=> Remove flit config from pyproject.toml

pyproject.toml, src/pytest_check/__init__.py, src/pytest_check/check_functions.py, src/pytest_check/check_log.py, src/pytest_check/check_raises.py, src/pytest_check/context_manager.py, src/pytest_check/plugin.py, src/pytest_check/pseudo_traceback.py, tox.ini
Closes #163.
Drops support for Python 3.8, which went end of life on 2024-10-07. Supporting it while adding type hints presented additional challenges.
Adds type hints in as narrow a way as I could manage while trying to avoid changes to the API. Also adds mypy checking to the tox file.
=> Adds type hinting; drops python 3.8

src/pytest_check/plugin.py, tox.ini
pluggy added type checking support and exposed `pluggy.Result` in 1.3.0.
Older `pluggy` versions must be supported as they are supported by `pytest`.
To avoid ImportError in environments with `pluggy<1.3.0` import `pluggy.Result` only during type checking.
Specify `pluggy` version supporting type checking in `mypy` and `mypy_earliest` tox environments.
Closes #176.
=> Fix pluggy.Result import for pluggy<1.3.0

src/pytest_check/pseudo_traceback.py
Before this patch, 
filenames in stacktrace only displayed its basename. This caused that it's not possible to navigate to them clicking on the pycharm terminal.
after this patch, the relative path is displayed, and it's possible to click on the files
=> show path in stacktrace

src/pytest_check/__init__.py
raises & any_failures exported from top `__init__.py `module so that mypy does not complain that they are not explicitly exported. More info at https://stackoverflow.com/a/79374189/145289
```
test/utils/test_math.py:20: error: Module "pytest_check" does not explicitly export attribute "raises"  [attr-defined]
with check.raises(ValueError):
```
=> export raises & any_failures

README.md, changelog.md, examples/test_example_raises.py, src/pytest_check/check_raises.py, tests/test_raises.py
1. Adds the exception value to the `CheckRaisesContext` object coming out of `raises`.
2. Tests and examples were added. 
Resolves https://github.com/okken/pytest-check/issues/185
=> Support getting exception value in raises
